name: Build Docker Image, Push it to Github Packages and Send notification to Slack Afterwards
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action  
        uses: actions/checkout@v2
        with:
          repository: thinknyx-technologies-llp/notify
          token: ${{ secrets.REPO_TOKEN }}
          path: ./
      - name: Docker Login & Pull Image
        run: echo  ${{ secrets.REPO_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin && docker pull ghcr.io/thinknyx-technologies-llp/notify:latest
      - name: Send a Notification
        id: notify
        uses: ./
        with:
          teams_webhook_url: ${{ secrets.TEAMS_HOOK }}
          message: "Github Action Completed for ${{ github.repository	 }} with Build Number ${{ github.run_number }} and the outcome is  ${{ needs.build.result }}."
